### ISSUE TITLE
Would be useful for listgroup to take a parameter.

### ISSUE THREAD

**Issue by huxoll** [cloudtools/gghelper#7]
I'd like to use gghelper to check if a Greengrass group exists before creating it (for multi-user, idempotent use).  I thought that listgroup would take a parameter to support that, but it lists the most recently created group instead.

I would like to run
```
$ gghelper listgroup -name mygroup
# Nonzero return code? Message "No such group is available."? Or just:
# group: {}
# Not found, therefore I can run
$ gghelper creategroup -name mygroup
```

This would allow gghelper to be used in CI and DevOps contexts.

**Comment by markpeek** [comment]
Thanks for the issue. Should work close to your specification with the error code being returned.
